### PR TITLE
ENG-876: Merge user configs with default values

### PR DESCRIPTION
**Pull request by marrony**

### CODE REVIEW

**Comment by benjumanji** [comment]
I'd consider using [envsubst](https://linux.die.net/man/1/envsubst). You could use standard bash defaulting to merge into vars and then write those vars out to a templated file. It would make both the script and the template easier to audit.

**Comment by marrony** [comment]
I never used `envsubst`, but looking at the internet it needs a pre-existent file to replace the env vars? is there any other benefit besides having a separate file to audit? I would also have to make my var `export`ed right?

**Comment by marrony** [comment]
@benjumanji I'll take a deeper look on `envsubst` and if I understand it correctly I will file a separate pr for it

**Comment by benjumanji** [comment]
@marrony it reads in stdin, but if you do that you may as well just use cat / heredoc as you were. You don't need to export anything special, just call it with regular bash semantics. Anyway, minor comment, the PR was fine as was.

**Pull request merged**
